#!/usr/bin/env bash
# anti-slop scanner — fast pattern scan for the highest-frequency slop categories.
# Usage:
#   scripts/scan.sh              # scan staged files
#   scripts/scan.sh --diff HEAD~3 # scan files changed since N commits ago
#   scripts/scan.sh path/to/dir  # scan a directory
#
# Exits 0 if score < 4 (CLEAN or ACCEPTABLE), 1 otherwise.

set -uo pipefail

SCORE=0
FINDINGS=()

# --- Determine file list ---
if [[ "${1:-}" == "--diff" ]]; then
  FILES=$(git diff --name-only "$2" --diff-filter=AM)
elif [[ -n "${1:-}" && -d "$1" ]]; then
  FILES=$(find "$1" -type f \( -name "*.py" -o -name "*.js" -o -name "*.ts" -o -name "*.tsx" -o -name "*.jsx" -o -name "*.go" -o -name "*.rs" -o -name "*.rb" \))
else
  FILES=$(git diff --cached --name-only --diff-filter=AM)
fi

if [[ -z "$FILES" ]]; then
  echo "anti-slop: nothing to scan."
  exit 0
fi

# --- Scanning helpers ---

flag() {
  local severity="$1" weight="$2" file="$3" line="$4" rule="$5" snippet="$6"
  FINDINGS+=("[$severity] $file:$line — $rule")
  FINDINGS+=("    $snippet")
  SCORE=$((SCORE + weight))
}

scan_secrets() {
  # CRITICAL — secrets
  while IFS=: read -r file line content; do
    flag "CRITICAL" 4 "$file" "$line" "possible secret in source" "$content"
  done < <(grep -nHE "(sk_live_|sk_test_|pk_live_|ghp_|github_pat_|xox[abps]-|AKIA[0-9A-Z]{16}|AIza[0-9A-Za-z_-]{35}|sk-ant-api[0-9a-zA-Z_-]+|hf_[a-zA-Z0-9]{30,}|glpat-[0-9a-zA-Z_-]{20,}|eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+)" $FILES 2>/dev/null || true)

  while IFS=: read -r file line content; do
    flag "CRITICAL" 4 "$file" "$line" "private key in source" "$content"
  done < <(grep -nHE "BEGIN (RSA|OPENSSH|EC|PGP|DSA) PRIVATE KEY" $FILES 2>/dev/null || true)
}

scan_debug_residue() {
  # LOW — debug residue
  while IFS=: read -r file line content; do
    flag "LOW" 1 "$file" "$line" "debug residue (console.log/print/breakpoint/debugger)" "$content"
  done < <(grep -nHE "(console\.(log|debug)|^\s*print\(|debugger;|breakpoint\(\)|pdb\.set_trace|pp\s*\()" $FILES 2>/dev/null | grep -v "node_modules" | grep -v "\.test\." | grep -v "_test\." || true)
}

scan_hedging() {
  # MEDIUM — hedging language in comments
  while IFS=: read -r file line content; do
    flag "MEDIUM" 2 "$file" "$line" "hedging language in code/comment" "$content"
  done < <(grep -nHEi "(// |# |/\* )(should work|hopefully|for now|quick fix|not sure|i think this|temporary|hack|workaround)" $FILES 2>/dev/null || true)
}

scan_stubs() {
  # HIGH — stubs and placeholders
  while IFS=: read -r file line content; do
    flag "HIGH" 3 "$file" "$line" "naked TODO/FIXME without owner or issue" "$content"
  done < <(grep -nHE "(// |# |/\* )(TODO|FIXME|XXX)([^(:]|$)" $FILES 2>/dev/null || true)

  while IFS=: read -r file line content; do
    flag "HIGH" 3 "$file" "$line" "NotImplementedError / not implemented stub" "$content"
  done < <(grep -nHE "(NotImplementedError|throw new Error\(['\"](not implemented|TODO))" $FILES 2>/dev/null || true)
}

scan_ai_markers() {
  # HIGH — AI marker comments
  while IFS=: read -r file line content; do
    flag "HIGH" 3 "$file" "$line" "AI marker comment" "$content"
  done < <(grep -nHEi "(added by (claude|cursor|copilot|ai|gpt)|ai[- ]generated|generated by (claude|ai)|claude wrote)" $FILES 2>/dev/null || true)
}

scan_commented_code() {
  # LOW — large blocks of commented-out code (heuristic: 3+ consecutive lines starting with //)
  for file in $FILES; do
    [[ -f "$file" ]] || continue
    awk '
      /^\s*\/\// { count++; if (count == 3) { print FILENAME ":" NR-2 ":" $0; exit_now=1 } next }
      /^\s*#/    { count++; if (count == 3 && FILENAME ~ /\.py$/) { print FILENAME ":" NR-2 ":" $0; exit_now=1 } next }
      { count = 0 }
    ' "$file" 2>/dev/null | head -3 | while IFS=: read -r f l c; do
      flag "LOW" 1 "$f" "$l" "block of commented-out code" "$c"
    done
  done
}

scan_python_specific() {
  # CRITICAL — mutable defaults, bare except
  for file in $FILES; do
    [[ "$file" == *.py ]] || continue
    while IFS=: read -r line content; do
      flag "CRITICAL" 4 "$file" "$line" "mutable default argument" "$content"
    done < <(grep -nE "def [a-zA-Z_][a-zA-Z0-9_]*\([^)]*=\s*(\[\]|\{\}|set\(\))" "$file" 2>/dev/null || true)

    while IFS=: read -r line content; do
      flag "HIGH" 3 "$file" "$line" "bare except clause" "$content"
    done < <(grep -nE "^\s*except\s*:" "$file" 2>/dev/null || true)
  done
}

scan_cross_language_python() {
  # MEDIUM — JS/Java idioms in Python files
  for file in $FILES; do
    [[ "$file" == *.py ]] || continue
    while IFS=: read -r line content; do
      flag "MEDIUM" 2 "$file" "$line" "JS idiom in Python (.push, .length, console.log, ===, const)" "$content"
    done < <(grep -nE "(\.push\(|\.length(\s|$|[^a-zA-Z])|console\.log|===|^\s*const\s+[a-zA-Z_])" "$file" 2>/dev/null || true)
  done
}

# --- Run scans ---
scan_secrets
scan_debug_residue
scan_hedging
scan_stubs
scan_ai_markers
scan_commented_code
scan_python_specific
scan_cross_language_python

# --- Verdict ---
if [[ $SCORE -eq 0 ]]; then
  VERDICT="CLEAN"
elif [[ $SCORE -le 3 ]]; then
  VERDICT="ACCEPTABLE"
elif [[ $SCORE -le 7 ]]; then
  VERDICT="NEEDS WORK"
elif [[ $SCORE -le 14 ]]; then
  VERDICT="SLOPPY"
else
  VERDICT="DUMPSTER FIRE"
fi

echo ""
echo "============================================"
echo "  anti-slop scan: $SCORE — $VERDICT"
echo "============================================"

if [[ ${#FINDINGS[@]} -gt 0 ]]; then
  printf "%s\n" "${FINDINGS[@]}"
fi

# Exit 1 if NEEDS WORK or worse, so this can be used as a pre-commit hook
if [[ $SCORE -ge 4 ]]; then
  exit 1
fi
exit 0
